name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        include:
          - os: ubuntu
            arch: amd64
          - os: ubuntu
            arch: arm64
          - os: windows
            arch: amd64
          - os: macos
            arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Set environment variables
      run: |
        echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
        echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV

    - name: Download and extract dist
      run: |
        REPO="chord-dht/chord-frontend"
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/$REPO/releases/latest | grep "browser_download_url.*dist.tar.gz" | cut -d '"' -f 4)
        curl -L -o dist.tar.gz $LATEST_RELEASE
        tar -xzf dist.tar.gz

    - name: Build
      run: |
        GOOS=$GOOS GOARCH=$GOARCH go build -o chord-client
    
    - name: Create release artifact
      run: |
        mkdir -p release
        mv chord-client release/
        mv dist release/
        tar -czf chord-client-${GOOS}-${GOARCH}.tar.gz -C release .
    
    - name: Get the current version
      id: get_version
      run: echo ::set-output name=version::$(date +'%Y.%m.%d.%H%M%S')

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release ${{ steps.get_version.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        files: ./chord-client-${GOOS}-${GOARCH}.tar.gz
        generate_release_notes: true