name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and extract dist
      run: |
        REPO="chord-dht/chord-frontend"
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/$REPO/releases/latest | grep "browser_download_url.*dist.tar.gz" | cut -d '"' -f 4)
        curl -L -o dist.tar.gz $LATEST_RELEASE
        tar -xzf dist.tar.gz

    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  build:
    needs: download
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o chord-client
    
    - name: Create release artifact
      run: |
        mkdir -p release
        mv chord-client release/
        mv dist release/
        tar -czf chord-client-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C release .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chord-client-${{ matrix.os }}-${{ matrix.arch }}
        path: chord-client-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts (linux/amd64)
      uses: actions/download-artifact@v4
      with:
        name: chord-client-linux-amd64
        path: ./release
    - name: Download artifacts (linux/arm64)
      uses: actions/download-artifact@v4
      with:
        name: chord-client-linux-arm64
        path: ./release
    - name: Download artifacts (windows/amd64)
      uses: actions/download-artifact@v4
      with:
        name: chord-client-windows-amd64
        path: ./release
    - name: Download artifacts (darwin/arm64)
      uses: actions/download-artifact@v4
      with:
        name: chord-client-darwin-arm64
        path: ./release

    - name: Get the current version
      id: get_version
      run: echo "version=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.version }}
        name: Release ${{ env.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        files: ./release/*.tar.gz
        generate_release_notes: true