name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and extract dist
      run: |
        REPO="chord-dht/chord-frontend"
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/$REPO/releases/latest | grep "browser_download_url.*dist.tar.gz" | cut -d '"' -f 4)
        curl -L -o dist.tar.gz $LATEST_RELEASE
        tar -xzf dist.tar.gz

    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  build:
    needs: download
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'

    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o chord-client
    
    - name: Create release artifact
      run: |
        mkdir -p release
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          mv chord-client release/chord-client.exe
        else
          mv chord-client release/
        fi
        mv dist release/
        zip -r chord-client-${{ matrix.os }}-${{ matrix.arch }}.zip release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chord-client-${{ matrix.os }}-${{ matrix.arch }}
        path: chord-client-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download linux-amd64 artifact
      uses: actions/download-artifact@v4
      with:
        name: chord-client-linux-amd64
        path: ./release

    - name: Download linux-arm64 artifact
      uses: actions/download-artifact@v4
      with:
        name: chord-client-linux-arm64
        path: ./release

    - name: Download windows-amd64 artifact
      uses: actions/download-artifact@v4
      with:
        name: chord-client-windows-amd64
        path: ./release

    - name: Download darwin-arm64 artifact
      uses: actions/download-artifact@v4
      with:
        name: chord-client-darwin-arm64
        path: ./release

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        files: ./release/*.zip
        generate_release_notes: true